name: CMake-Linux

on:
  push:
    branches:
      - main
      - jsoncpp
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Dependencies
        run: git submodule init && git submodule update

      - name: Configure JSONCPP
        run: |
            cd lib/jsoncpp
            mkdir build && cd build
            cmake ..
            make -j12
            sudo make install
            cd ../../..

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cd build && make -j8

