name: CMake-Linux

on:
  push:
    branches:
      - main
      - jsoncpp
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Stuffs
        run: sudo apt-get install -y libjsoncpp-dev

      - name: Configure CMake
        run: git submodule init && git submodule update && cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cd build && make -j8

