name: Man Gen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  Generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Pandoc
        run: sudo apt install pandoc -y

      - name: Generate Docs
        run: |
          cd docs
          pandoc appnotexManpage.md -s -t man -o appnotex.1
