name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Create Dir
        run: make builddir && mkdir -p data/test
      
      - name: Configure CMake
        run: git submodule init && git submodule update && cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cd build && make -j8 && cd ..

      - name: appnotexTest
        run: cd bin && ./appnotexTest
